name: verify

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: ログレベル
        default: warning
        
jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    strategy:
      matrix:
        python-version:
        - 'pypy3.10' # 一番AtCoder環境に近いバージョン
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip3 install -U git+https://github.com/edomonndo/verification-helper.git

    - name: Get dropbox token
      env:
        DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
        DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      run:  |
          {
            echo 'DROPBOX_TOKEN<<EOF'
            curl --silent https://api.dropbox.com/oauth2/token \
            -u ${DROPBOX_APP_KEY}:${DROPBOX_APP_SECRET} \
            -d grant_type=refresh_token \
            -d refresh_token=${DROPBOX_REFRESH_TOKEN} \
            | jq -r .access_token
            echo EOF
          } >> "$GITHUB_ENV"

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        PYTHONPATH: /home/runner/work/edomonndo/python-library
      run: oj-verify all --timeout 1200
