name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - 'pypy3.12' # 一番AtCoder環境に近いバージョン
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper importlab
      
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        PYTHONPATH: /home/runner/work/edomonndo/python-library
      run: oj-verify all --timeout 1200
